apiVersion: apps/v1
kind: Deployment

metadata:
  name: jenkins-proj-101-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-proj-101-backend
  template:
    metadata:
      labels:
        app: jenkins-proj-101-backend
    spec:
      containers:
        - name: jenkins-proj-101-backend
          image: sohan0077/jenbackend:v1
          ports:
            - containerPort: 8000

---

apiVersion: v1
kind: Service
metadata:
  name: jenkins-proj-101-backend
spec:
  selector:
    app: jenkins-proj-101-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: NodePort
