apiVersion: apps/v1
kind: Deployment

metadata:
  name: jenkins-proj-101-backend
spec:
  replicas: 4
  selector:
    matchLabels:
      app: jenkins-proj-101-backend
  template:
    metadata:
      labels:
        app: jenkins-proj-101-backend
    spec:
      # initContainers:
      #   - name: init-service
      #     image: busybox
      #     command: ['sh', '-c' , 'echo waiting... && sleep 15']

      containers:
        - name: jenkins-proj-101-backend
          image: sohan0077/jenbackend:6da2f15
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "100m" ## REQUIRED FOR HPA
            limits:
              cpu: "200m"

---

apiVersion: v1
kind: Service
metadata:
  name: jenkins-proj-101-backend
spec:
  selector:
    app: jenkins-proj-101-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: NodePort